---
collections:
  # Cisco IOS
  - name: cisco.ios
    version: "9.2.0"
  
  # Réseau - base
  - name: ansible.netcommon
    version: "7.2.0"
  
  # Utilitaires
  - name: ansible.utils
    version: "5.1.2"
  
  # Modules généraux
  - name: community.general
    version: "9.5.0"
