---
collections:
  - name: cisco.ios
    version: ">=9.0.0,<10.0.0"
  
  - name: ansible.netcommon
    version: ">=7.0.0,<8.0.0"
  
  - name: ansible.utils
    version: ">=5.0.0,<6.0.0"
  
  - name: community.general
    version: ">=9.0.0,<10.0.0"
